use quiz;

insert into users (username, password, highscore) values
    ("andrei", "123", 0),
    ("marius", "123", 0),
    ("giulia", "123", 0);

insert into questions (text) values
    ('What is the capital of Australia?'),
    ('Who wrote the novel "To Kill a Mockingbird"?'),
    ('What is the chemical symbol for sodium?'),
    ('Which planet is known as the "Red Planet"?'),
    ('Who painted the famous artwork "The Starry Night"?'),
    ('What is the largest ocean on Earth?'),
    ('In which year did World War II end?'),
    ('Who is the founder of Microsoft?'),
    ('Which country is known for its tulips and windmills?'),
    ('What is the highest mountain in the world?'),
    ('Who painted the "Mona Lisa"?'),
    ('What is the largest planet in our solar system?'),
    ('What is the capital of Japan?'),
    ('Which scientist developed the theory of relativity?'),
    ('What is the chemical symbol for iron?'),
    ('Who is the author of the "Harry Potter" book series?'),
    ('What is the tallest mammal on Earth?'),
    ('Which country is home to the Pyramids of Giza?'),
    ('In which city is the Eiffel Tower located?'),
    ('What is the currency of Brazil?');

insert into answers (text, isCorrect, questionId) values
    ('Canberra', true, 1),
    ('Sydney', false, 1),
    ('Melbourne', false, 1),
    ('Perth', false, 1),
    ('Harper Lee', true, 2),
    ('F. Scott Fitzgerald', false, 2),
    ('George Orwell', false, 2),
    ('Ernest Hemingway', false, 2),
    ('Na', true, 3),
    ('S', false, 3),
    ('So', false, 3),
    ('Sn', false, 3),
    ('Mars', true, 4),
    ('Jupiter', false, 4),
    ('Venus', false, 4),
    ('Saturn', false, 4),
    ('Vincent van Gogh', true, 5),
    ('Leonardo da Vinci', false, 5),
    ('Pablo Picasso', false, 5),
    ('Salvador Dali', false, 5),
    ('Pacific Ocean', true, 6),
    ('Atlantic Ocean', false, 6),
    ('Indian Ocean', false, 6),
    ('Arctic Ocean', false, 6),
    ('1945', true, 7),
    ('1918', false, 7),
    ('1939', false, 7),
    ('1955', false, 7),
    ('Bill Gates', true, 8),
    ('Steve Jobs', false, 8),
    ('Mark Zuckerberg', false, 8),
    ('Larry Page', false, 8),
    ('Netherlands', true, 9),
    ('France', false, 9),
    ('Germany', false, 9),
    ('Italy', false, 9),
    ('Mount Everest', true, 10),
    ('K2', false, 10),
    ('Kangchenjunga', false, 10),
    ('Makalu', false, 10),
    ('Leonardo da Vinci', true, 11),
    ('Vincent van Gogh', false, 11),
    ('Pablo Picasso', false, 11),
    ('Salvador Dali', false, 11),
    ('Jupiter', true, 12),
    ('Saturn', false, 12),
    ('Mars', false, 12),
    ('Neptune', false, 12),
    ('Tokyo', true, 13),
    ('Beijing', false, 13),
    ('Seoul', false, 13),
    ('Bangkok', false, 13),
    ('Albert Einstein', true, 14),
    ('Isaac Newton', false, 14),
    ('Charles Darwin', false, 14),
    ('Stephen Hawking', false, 14),
    ('Fe', true, 15),
    ('Au', false, 15),
    ('Ag', false, 15),
    ('Cu', false, 15),
    ('J.K. Rowling', true, 16),
    ('George R.R. Martin', false, 16),
    ('J.R.R. Tolkien', false, 16),
    ('Dan Brown', false, 16),
    ('Giraffe', true, 17),
    ('Elephant', false, 17),
    ('Hippopotamus', false, 17),
    ('Lion', false, 17),
    ('Egypt', true, 18),
    ('Greece', false, 18),
    ('Italy', false, 18),
    ('India', false, 18),
    ('Paris', true, 19),
    ('London', false, 19),
    ('Berlin', false, 19),
    ('Rome', false, 19),
    ('Brazilian Real', true, 20),
    ('Euro', false, 20),
    ('Yen', false, 20),
    ('Dollar', false, 20);